<a href="https://colab.research.google.com/github/Tushin-AS/CoLab_learning/blob/main/PracticeLearning004_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Dummy Variables**

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("homeprices2.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [3]:
df.describe

<bound method NDFrame.describe of                town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000>

In [5]:
dummies = pd.get_dummies(df.town, dtype= int)
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [7]:
merged_db = pd.concat([df, dummies], axis= 'columns')
merged_db

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

In [9]:
final_db = merged_db.drop(['town', 'monroe township'], axis= 'columns')
final_db

    area   price  robinsville  west windsor
0   2600  550000            0             0
1   3000  565000            0             0
2   3200  610000            0             0
3   3600  680000            0             0
4   4000  725000            0             0
5   2600  585000            0             1
6   2800  615000            0             1
7   3300  650000            0             1
8   3600  710000            0             1
9   2600  575000            1             0
10  2900  600000            1             0
11  3100  620000            1             0
12  3600  695000            1             0

In [13]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [15]:
X = final_db.drop(['price'], axis= 'columns')
X

    area  robinsville  west windsor
0   2600            0             0
1   3000            0             0
2   3200            0             0
3   3600            0             0
4   4000            0             0
5   2600            0             1
6   2800            0             1
7   3300            0             1
8   3600            0             1
9   2600            1             0
10  2900            1             0
11  3100            1             0
12  3600            1             0

In [16]:
Y = final_db.price
Y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [17]:
model.fit(X,Y)

LinearRegression()

In [19]:
model.predict([[2800, 0, 0]]) # Area, Robinsville(A,1,0), West Windsor(A,0,1); Monroe Township(A,0,0)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([565089.22812298])

In [20]:
model.predict([[3400, 1, 0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([666914.10449366])

In [21]:
model.score(X,Y)

0.9573929037221871